generate_matrices: generate_matrices.cpp
	g++ generate_matrices.cpp -o generate_matrices
	./generate_matrices

one_thread: one_thread.cpp
	g++ one_thread.cpp -o one_thread

multi_thread: multi_thread.cpp
	g++ multi_thread.cpp -pthread -o multi_thread
